### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by cmeesters** [s-andrews/FastQC#104]
Hi,

b1d8681e62ba9f8d8947f37a9b93ef82aba6ab6e fixes #75, #86 and #88 according to the commit note. This fix is from 8. June. The last release, however, is from 8. Jan. 2020 .

Would this not merit a new release?

Best regards
Christian

**Comment by serge2016** [comment]
Same here! It would be great to get a new release!

**Comment by ialarmedalien** [comment]
@s-andrews Any chance of this happening?

**Comment by serge2016** [comment]
Hope to see new release very much)

**Comment by cmeesters** [comment]
Thing is that package maintainer rely on releases and do not necessarily "just ship as is".

**Comment by tmancill** [comment]
@s-andrews I am making one more appeal to tag a release before the Debian [bookworm freeze](https://release.debian.org/bookworm/freeze_policy.html), which will occur on February 12th, 2023.

A released version of FastQC is cleaner than the alternative, which is for Debian to release with a version `0.11.9+git${DATE}-${SHA_SHORT_HASH}` that accumulates fixes since the 0.11.9 release.  Having the commit SHA as part of the version can be confusing for users (and maintainers), and the (Debian) release will be extant for several years.  Ubuntu will pick up the latest Debian version as well (see [repology for fastqc](https://repology.org/project/fastqc/packages)).  The other alternative is to let Debian release with 0.11.9 as-is.

Thank you for considering it.

**Comment by lparsons** [comment]
A new tagged release would be most welcome. It would also benefit other packaging systems like [Bioconda](https://bioconda.github.io/).

**Comment by s-andrews** [comment]
Yeah, it's basically all done and ready to go.  I just need to do some testing on OSX before I can push it.  I've checked other platforms so I don't think there should be a problem.

**Comment by cmeesters** [comment]
> It would also benefit other packaging systems like [Bioconda](https://bioconda.github.io/).

Yep, I would push to the [easyconfigs](https://github.com/easybuilders/easybuild-easyconfigs) repo. As so many seem to read along, I just want to take the opportunity, to point out, that there are more than 1 or 2 package maintainers out there who will profit from releases under semantic versioning.

I really appreciate your effort @s-andrews !

**Comment by lparsons** [comment]
Great to hear @s-andrews! Thanks for the excellent software and continued support, I know it's a lot of work to maintain something so popular.

**Comment by s-andrews** [comment]
FastQC v0.12.1 is now out and available to download.  Sorry for the delay but we kept finding blocker bugs in testing.

Please report any issues you find in the new version, or any old issues which this doesn't resolve.
