### ISSUE TITLE
Adapter searching truncated?

### ISSUE THREAD

**Issue by dnasko** [s-andrews/FastQC#105]
Hi!

Love the tool, but had a quick question! The Adapter Content plot's X-axis never makes it to the end of the expected distribution of read lengths. E.g. I have a run with 150BP data, I would expect there to be some last window of 145-150BP on the Adapter Content plot, but the last bin I see is usually way smaller than that, maybe 110-115.

Other plots in the report make it to the expected read size.

Is this to be expected?

Thank you!

**Comment by FelixKrueger** [comment]
The adapter content module is looking for exact matches of various adapter sequences, and then reports the beginning of the adapter sequence as a cumulative occurrence. Since the adapter sequences are typically in the range of 12-15bp (see the file `adapter_list.txt` within the FastQC configuration folder) you may not find a full sequence match on the very 3' end of sequences, which is why the adapter content plot stops short of the full read length.

**Comment by dnasko** [comment]
Hi Felix, thank you for the quick response and clarifying what I suspected to be the answer!
