### ISSUE TITLE
can not run fastqc in non-interactive mode on windows

### ISSUE THREAD

**Issue by alex297** [s-andrews/FastQC#11]
I am trying to run fastqc analysis in non-interactive mode on Windows. I installed FastQC and can run run_fastqc.bat in interactive mode. But I could not run the wrapper fastqc in cmd or ubuntu. cmd does not recongise chmod commamn). And ubuntu does not run run_fastqc.bat at all. I am new to Linux, just installed ubuntu and I can see the file run_fastqc.bat in directory (/mnt/c/Users/...). But ubuntu does not run run_fastqc. So my main question is how to run fastqc non-interactively on windows? But also I would like to know how to run it from ubuntu. Would be grateful for any feedback. Alex

**Comment by s-andrews** [comment]
There are two launch scripts for fastqc, the bat file which is only used on windows, and the 'fastqc' perl script which is used on OSX and linux.  The non-interactive mode for fastqc currently only works when fastqc is launched via the perl script.  I've looked at modifying the bat file to allow that to work too, but it turns out not to be so simple.

The answer to your question is therefore that you need to install a perl distribution onto your windows machine.  We use ActivePerl, but there are plenty of others around.  Once you've done that then you should be able to do something like:

```
perl c:\programs\FastQC\fastqc myfile.fq.gz
```

...and it should then process that file non-interactively.

**Comment by alex297** [comment]
Thank you
