### ISSUE TITLE
Error: Could not find or load main class uk.ac.babraham.FastQC.FastQCApplication

### ISSUE THREAD

**Issue by YueWenbo** [s-andrews/FastQC#126]
```
Error: Could not find or load main class uk.ac.babraham.FastQC.FastQCApplication
Caused by: java.lang.ClassNotFoundException: uk.ac.babraham.FastQC.FastQCApplication
```

Hi, I got this error when trying to install FastQC v0.12.1.

I tried to troubleshooting but none of the methods worked. I can't tell if the file `fastqc_v.12.1.zip` is binary or not, I couldn't find a download link for binary as that's seems to be the only download link. 

My java version is 

```
$ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```

Any solutions?

Thank you.

**Comment by s-andrews** [comment]
The download link you want is:

https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip

You probably have the correct file as if it was the source distribution you should get a specific error saying that this is the source distribution and not the error you actually got.

The most likely reason for this failure is that your installation is incomplete so the necessary .class files are actually missing.  I'd suggest re-downloading and unzipping the distribution files and trying again.  If you get the same error then look in the FastQC folder and check you can see the file uk/ac/babraham/FastQC/FastQCApplication.class because if you can't then that's the root cause of the problem.

Let me know if you're still having problems.

**Comment by YueWenbo** [comment]
Thank you for your response.

I tried to re-download and install, but the problem still remains. The .class file is there, so I think the problem is due to the java installed on the server I am using, because I am trying to use another java based tool and it also report java error. I'll try to connect to our admin team to solve the problem. 

Thanks again.
