### ISSUE TITLE
Unrecognized VM option '+ExitOnOutOfMemoryError'

### ISSUE THREAD

**Issue by mad0c** [s-andrews/FastQC#134]
Error on first startup:

 ./fastqc -v
Unrecognized VM option '+ExitOnOutOfMemoryError'
Could not create the Java virtual machine.

Java Version:
Java(TM) SE Runtime Environment (build 1.6.0_27-b07)
Java HotSpot(TM) 64-Bit Server VM (build 20.2-b06, mixed mode)

OS: "Scientific Linux 7.3 (Nitrogen)"
FastQC v0.12.1

seems to be caused by this line in the fastqc startup script:
https://github.com/s-andrews/FastQC/blob/1faeea0412093224d7f6a07f777fad60a5650795/fastqc#L77

**Comment by s-andrews** [comment]
So this option was added a while back because without it if the JVM runs out of memory then it just hangs indefinitely and doesn't exit, so can cause havoc on clusters where you just get a ton of stuck jobs.

I wasn't aware that this option hadn't always been in java, but looking a bit harder it was introduced in java8 (u92) which came out in April 2016 and is the oldest currently supported java version.  You appear to be running java 6 which has now been end of life since 2013, so I think that the benefits of this option outweigh the issues with really old JVMs.

If you want to apply a simple fix to your system then you can just comment out that line and that will get you further.  I'm not sure I'd guarantee that there won't be something else in the codebase which will cause problems on a JVM that old.  We don't test that far back any more, and I suspect things like htslib probably won't be compiled for that level of compatibility any more.

The simplest fix is to just update to java 8 or higher and you should be good.
