### ISSUE TITLE
 [Java Error] Can't connect to X11 window server using ___ as the value of the DISPLAY variable.

### ISSUE THREAD

**Issue by hbhutta** [s-andrews/FastQC#142]
Hi,

I am trying to run fastqc from within a singularity container, and I get the specified error message. I have tried different solutions on stack exchange about exporting the DISPLAY variable, but nothing is working. I am just trying to do a test run of ./fastqc on some paired reads.

This is the version I am using (checked from within a conda environment within a singularity container): 
```
(salmon110) Singularity> ./fastqc --version
FastQC v0.11.8
```
This is the full error message:
![image](https://github.com/user-attachments/assets/08fcb4f4-9f46-465d-9a40-75f32269747c)

Any help would be appreciated.

**Comment by s-andrews** [comment]
As you've probably found in your previous searches, the problem with your X11 setup isn't specific to fastqc in any way - it would affect any program connecting to a display on your machine.

If you're running this from inside a container it's probably easier if you just run fastqc in batch mode to generate an HTML report rather than running the interactive application.  To do this you just add the name of the file(s) you want to analyse to the command line:

```fastqc file1.fastq.gz file2.fastq.gz```

..for example.  That should get you a report you can look at in a web browser.

If you find you're getting an error similar to your original post when specifying the file names on the command line then try running:

```
unset DISPLAY
```

in your shell before running the command as that may fix things.
