### ISSUE TITLE
Kmer Profiles Image generation

### ISSUE THREAD

**Issue by apaala** [s-andrews/FastQC#15]
I see that the new version does not generate the kmer profile by default. I was wondering why that decision was made and what flag I could use in order to generate it.

**Comment by s-andrews** [comment]
Sorry, short reply as I'm on a phone - there should be a longer explanation in the release notes if you want to have a look.

The kmer plot was turned off by default partly because many (but not all)  the problems it could spot are easier to find from one of the other modules. Also, it tended to give false positive warnings and worry people about data which was actually ok. There is still some utility to it, but on balance we felt it was better to turn it off in the default configuration.

If you want to re-anable it then edit the limits.txt file in the Configuration directory of the install and set kmer back to 1. If you can't change the installed files then you can edit a copy of that file and use the --limits option to pass it when running the program.

**Comment by apaala** [comment]
Hi

I appreciate your response and the reasoning makes a lot of sense.

I checked the limits file and it already has the kmer set to 1.

Below is a snippet of the limits file
duplication             ignore          0
kmer                            ignore          1
n_content                       ignore          0
overrepresented         ignore          0
quality_base            ignore          0
sequence                        ignore          0
gc_sequence                     ignore          0
quality_sequence        ignore          0
tile                            ignore          0
sequence_length         ignore          0
adapter                         ignore          0

**Comment by apaala** [comment]
Hi 

Thanks for the response, I removed the "ignore" in the limits file and it generated an image. Appreciate your help!

**Comment by s-andrews** [comment]
Sorry, got it backwards. Set it to 0 to re-anable.
