### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by banan314** [s-andrews/FastQC#19]
```
Could not find or load main class uk.ac.babraham.FastQC.FastQCApplication
```
On both Linux and Windows :cry:

**Comment by s-andrews** [comment]
I suspect you might have downloaded the source code distribution instead of the binary distribution. The download you want is:

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.8.zip

Can you please double check that this is the one you're using. Thanks.

**Comment by banan314** [comment]
Of course, I downloaded the source code, because there isn't any binary on Github releases. The binary you provided works :ok:. Thanks.

**Comment by lefty556** [comment]
Possible to add the binary distro link also on github to save confusion?

**Comment by romunov** [comment]
I downloaded the source code (you can also `git clone`) and made the mistake of _copying_ `fastqc` to `/usr/local/bin/fastqc`. Soft linking did the trick, as _specified in the documentation_. :facepalm:

**Comment by s-andrews** [comment]
:-)

**Comment by erzakiev** [comment]
Dear @s-andrews, first of all thank you very much for the very awesome tool that is basically used by the whole academia world.

I normally work in linux environments but on this particular occasion I need to run fastqc on Windows. For that, I downloaded the version of the archive in the link you listed above. 

The `run_fastqc.bat` file only works when I am in the folder where I unpacked the fastqc archive to. Otherwise, when trying to run the file from any other folder it throws the `could not find or load main class` error. 


I tried: 1) soft-linking the `.bat` file and invoking it through that, and also 2) I added the folder with fastqc into the PATH variable, but... It still only works when I'm in the folder with the `run_fastqc.bat` file.

The insides of the bat file are pretty simple, but I'm not well versed with java and I assume that the problem lies in the fact that all the paths here are relative:
`java -Xmx250m -classpath .;./sam-1.103.jar;./jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication %*`

How can I modify the command to have absolute paths so that I can invoke it from wherever I want? 

Thanks in advance XOXO

**Comment by erzakiev** [comment]
Sorry for disturbance, I was able to follow the advice given here
https://stackoverflow.com/questions/14936625/relative-path-in-bat-script
and after replacing the dots `.` into `%~dp0`, it works now from any directory. The `.bat` file looks like that:

`java -Xmx250m -classpath %~dp0;%~dp0/sam-1.103.jar;%~dp0/jbzip2-0.9.jar uk.ac.babraham.FastQC.FastQCApplication %*`

**Comment by erzakiev** [comment]
Passing the usual arguments like number of threads `-t=<...>` or specifying the output directory with `-o` doesn't seem to work with the `.bat` file. How to circumvent that??
