### ISSUE TITLE
kmer failed 

### ISSUE THREAD

**Issue by whiteorchid** [s-andrews/FastQC#21]
Dear author, may I have your instruction how to filter or treat fastq file when the kmer test is failed, and the overrepresented kmer is in the middle of the read, great thanks!
![image](https://user-images.githubusercontent.com/6839620/48112946-a0c2f000-e293-11e8-9580-e46d353f8f7f.png)

**Comment by s-andrews** [comment]
Single position spikes like that are normally the result of a single over-represented sequence.  If you got anything in the over represented sequences module then the kmers from that will almost certainly show up in the kmer plot too.  Often you get sets of these which are the overlapping kmers and you can see that in your case, where the blue and red hits are the same sequence shifted by one base.  If you get a few of them then you can often read the offending sequence to find out what it is, but there isn't quite enough context here to do that.

The only really biased kmer (rather than a duplicated sequence) in this plot would be the black hit which rises towards the end of the sequence steadily and probably represents some kind of adapter.
