### ISSUE TITLE
ID line didn't start with '@' when fastqc fq.gz

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [s-andrews/FastQC#37]
Hi 
I am now fastqc 20 rawdata with FastQC v0.11.5.After finished I found there are 12 succeed but 8 failed with the following error:
`Started analysis of 93UV147-input_535.fq.gz
Failed to process file 93UV147-input_535.fq.gz
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
        at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
        at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:76)
        at java.lang.Thread.run(Thread.java:748)`
I have never met these problems before and I don't know how to deal with it.It means my data is broken and I should delete some lines?Could you please give me some suggestions?Thanks so much in advance.

**Comment by s-andrews** [comment]
Sorry, but those errors normally mean that the input file is corrupted.  FastQ files should always be sets of 4 lines where the first of each set starts with an @ and the third of each set starts with a +.  If this format isn't found then you get this error.  Often the problem will be right at the top of the file, so you can use something like:

```
zcat 93UV147-input_535.fq.gz | less -S
```

to look at the top of the file and see if you see anything unexpected in there.

**Comment by qiaowei-vvjoe** [comment]
yes.
@s-andrews 
I run it and it shows the following:
`
@CL100059197L2C001R001_10

GCCGAATGTGTTGGTGCACACCTGTTGTCCCAGCCCTTTGGGAGGTCAAG
+
FFF:F?=F=FFFFFFF=FFFFFFF:FFFFFF9FFFFFFFFFFFF<FE@FF
@CL100059197L2C001R001_15
CTCCATGTTGGTCCCAAGTGGGCAGTCATCCTGCCTTTGCTTTTCTCCAT
+
FFFGEEBEEFFE@GFEDFFFFGFGFFFGG>FFEFFGGFGGGEGGFEGGGG
@CL100059197L2C001R001_30
ACCTGGCAAGTATAATGCTGAAATACAGCCTACTGACAAGTATAATGCTG
+
EFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;FF
@CL100059197L2C001R001_38
GTCCTGGGATGAGCAAAATGAGATCAGAAACAACAATACAAAGGAAGGGG
+
DA@AE1@9AEA?0AFEFE7BABDA?FCD@EDEE?EAEE?FEC>6CED2C>
@CL100059197L2C001R001_55
TGATAAGCTACAAAGAACTACGGTTTTCGCTACTCTCAAAAAGCTACTGA
+
EAFFGFFFFFFFFAF?FGFFGF<DFEEFFFFF?FFFFFFFF?FFDEFFFC
@CL100059197L2C001R001_59
ATGTGTCAGTAAAAGGATTGTGTACTAGAACTTAAGGTATTGCTGACTAA
+
DEFDE@EEE=CC@BFEAAEF=FEFDEFFAEFEEF6FBDFEEEFDEB>FFF`
I just attached the first part but how can I know which line is corrupted? or how do fastqc deal with such problems?or I must use other qc tools?Thank you so much in advance.

**Comment by s-andrews** [comment]
You seem to have an extra blank line after the first line - that breaks the file and fastqc (and all other programs which deal with fastq data) won't be able to read it.

FastQ is such a simple format that generally there isn't any tolerance of mistakes within the file and the processing will just fail.  I guess the question is where the blank line came from - it wouldn't have been in the file generated by the sequencer so some previous processing step must have introduced it.  I'd suggest going back to the original data and finding where the file got changed.  You could potentially fix that single line, but we don't know that there is just a one line addition, or that there aren't further problems later in the file.

**Comment by qiaowei-vvjoe** [comment]
HI @s-andrews 
I am sorry but the blank in the first line is caused by myself when i copied it from terminal to this issue.I am very sorry it caused your misunderstanding.And the real first part file shows following:

@CL100059197L2C001R001_10
GCCGAATGTGTTGGTGCACACCTGTTGTCCCAGCCCTTTGGGAGGTCAAG
+
FFF:F?=F=FFFFFFF=FFFFFFF:FFFFFF9FFFFFFFFFFFF<FE@FF
@CL100059197L2C001R001_15
CTCCATGTTGGTCCCAAGTGGGCAGTCATCCTGCCTTTGCTTTTCTCCAT
+
FFFGEEBEEFFE@GFEDFFFFGFGFFFGG>FFEFFGGFGGGEGGFEGGGG
@CL100059197L2C001R001_30
ACCTGGCAAGTATAATGCTGAAATACAGCCTACTGACAAGTATAATGCTG
+
EFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;FF
@CL100059197L2C001R001_38
GTCCTGGGATGAGCAAAATGAGATCAGAAACAACAATACAAAGGAAGGGG
+
DA@AE1@9AEA?0AFEFE7BABDA?FCD@EDEE?EAEE?FEC>6CED2C>
@CL100059197L2C001R001_55
TGATAAGCTACAAAGAACTACGGTTTTCGCTACTCTCAAAAAGCTACTGA
+
EAFFGFFFFFFFFAF?FGFFGF<DFEEFFFFF?FFFFFFFF?FFDEFFFC
@CL100059197L2C001R001_59
ATGTGTCAGTAAAAGGATTGTGTACTAGAACTTAAGGTATTGCTGACTAA
+
DEFDE@EEE=CC@BFEAAEF=FEFDEFFAEFEEF6FBDFEEEFDEB>FFF
@CL100059197L2C001R001_65
AGGGGAATGGAATGGAATGGAATGCAATGGAATGGAATCATCCGGAATGG
+
GFFFFGEAFF@GEEFGDFFFFGEEGEGEFFBEFEFGDBFEEGEGBFEEEG

the data is rawdata without any process.
so you means fastqc cannot find which line is corrupted and I must find other tools to fix the problem?

**Comment by s-andrews** [comment]
That data you showed is OK, so it must be further down the file.  You can try to find where the error is, but to be honest if it's corrupted anywhere then you can't really trust the data.  You'd be better getting a fresh copy from your sequencing facility which isn't corrupted.

**Comment by qiaowei-vvjoe** [comment]
Sure.
@s-andrews 
I will report this problem to my PI cause this data is downloaded from Cloud disk by her.
Thank you so much for your patient explanation.

**Comment by sfourdrilis** [comment]
I had the same issue, and there was a string of characters at the beginning of the file, before the first read. But I couldn't see it on screen by executing the less command. I had to open the file in the nano text editor, and manually erase these characters.

**Comment by idiltac** [comment]
@sfourdrilis hi, ı am new in lınux and ı have same problem. My file is fast.gz file and I wonder how can i open file and erase manually without unzip file.

**Comment by s-andrews** [comment]
You can't directly edit a gzipped file.  The only way to change the contents is to uncompress it, edit it and recompress.  Having said that if you're getting this error then unless you know exactly how the odd content got into your file I'd be extrememly suspicious of the data.  Raw sequence files won't have this problem so something has corrupted your data and it will be difficult to know how much you can trust what is left.  I'd strongly suggest going back to the original data source and trying to get an uncorrupted copy if you can rather than trying to patch up the version you have.

**Comment by sfourdrilis** [comment]
Hi @idiltac 

I edited the unzipped file.
The string of characters that were before the first read was not from the raw data but was added afterwards. So I knew it was not data corruption, and I could delete it. It was something like a path to a server where the file was stored by the user.

I also had to delete a blank line at the end of the fastq file.

As I hadn't used nano before, it took me some time to use it properly. I am writing here how to use it, if it can help others save time!

1) In the linux terminal, go to the directory where your fastq file is located (using the cd command). Then, type the following command to open the file (it takes a while):

nano yourfilename.fastq

2) Move within the file using keyboard arrows to go on the @ symbol where the first read starts 

3) ^c (to indicate that the cursor position is here)

4) Press Enter. Thus, the read is now on line 2 of the file

5) Move back to line 1 using ^c

6) ^k (to delete line 1)

7) ^x (to quit nano; you will be prompted to save the file if not done before)

8) You are now back to the terminal and you can type the following in order to check that the line has been removed:

head yourfilename.fastq

**Comment by idiltac** [comment]
@sfourdrilis @s-andrews thanks a lot both of you, have a nice day :)

**Comment by khushbrar7** [comment]
I'm having this same problem, but the fastqc of raw reads was fine. I got this error after trimming the files using trimmomatic0.39. What I don't understand is how can a trimmer corrupt/ erase '@' in a fasta file? Anyone can help me understand would be great!

**Comment by AsudeBerber** [comment]
> I had the same issue, and there was a string of characters at the beginning of the file, before the first read. But I couldn't see it on screen by executing the less command. I had to open the file in the nano text editor, and manually erase these characters.

But in the fastq file, while we are doing analyses we can't erase by ourself just like that, right?

**Comment by s-andrews** [comment]
> But in the fastq file, while we are doing analyses we can't erase by ourself just like that, right?

Editing huge fastq files is not trivial.  Most editors are not designed to deal with files which are that big, nor can they cope with compressed files.  Depending on what the nature of the corruption is in your data there may be a nice command line option to fix it (ie skipping the first few lines), but there's so many ways that a fastq file can be messed up that it's difficult to suggest a general solution. 

A couple of things to try would be:

1) Using the ```less``` program to look at the start of your file to see if there's anything weird there.  Simply running ```less file.fq.gz``` (with your filename obviously) and seeing if there's something strange at the beginning, or whether the file even looks like a fastq file is a good start.

2) Checking that the whole file can decompress correctly is also good.  If a gzipped file is corrupted then it often generates a bunch of random output before it dies so this is also a good sanity check.  You can decompress the whole file and throw away the output to see if you see any errors from the decompressor.  Something like:

```zcat file.fq.gz > /dev/null```

..should work.

**Comment by superbioJM** [comment]
I had the similar issue, 

> didn't start with '+'

 my data is downloaded from Cloud disk，i use 'dos2unix' frist time ，and then get this err. 

 Then, I don't know how to deal with it . Could you please give me some suggestions?

**Comment by s-andrews** [comment]
FastQ files have a 4 line structure, something like:

```
@uniqueid
GATATTAGCTAG
+
BCCABBCBDEFH
```

Where line 1 is identifier and it always starts with \@
Line 2 are the base calls
Line 3 is the mid line and starts with a + (and is usually empty other than that)
Line 4 are the quality scores

FastQC does some basic checks that this structure is present, and if it isn't then that's the warning you get.  If the structure is broken then the most likely causes are:

1. Your file is corrupt or truncated - gzip decompressors sometimes spit out random rubbish when the file is corrupt or truncated before they die which can lead to these errors.
2. Something else is in the file before the data actually starts - some random header / bit of log file / whatever, and it's right at the top.
3. There is a broken sequence in the middle of the file somewhere.

Frankly in pretty much all of these cases the fix is to go back to the original source of the data and grab a new copy.  Even if you went through running a more clever validation and skipping the bits which looked wrong you'll never know what you threw away or how much more data would have been in the original file.  You could possibly fix 2 by looking at the to of the file and skipping a few lines, but that's about it.

**Comment by hellopeccat** [comment]
Check out whether your fq.gz files are indeed raw data rather than clean data, especially when they are downloaded from somewhere and maybe are already controlled for quality.
