### ISSUE TITLE
per base GC content failed

### ISSUE THREAD

**Issue by TendoLiu** [s-andrews/FastQC#39]
![test](https://user-images.githubusercontent.com/54043441/65261835-16fcc980-dad7-11e9-9f6e-ea38fcf0d876.jpg)

Hi guys, first time for me to analyze WGS data. Not sure if this is a concern for downstream analysis? If so, what could I do to improve the situation?

THanks.

**Comment by s-andrews** [comment]
This simply shows that you don't have a completely uniform GC content, and the library therefore doesn't look how you'd expect for a random genomic library from a single species (which is what the checks are based on). 

For some library types (eg ChIP) this could be fine since you're applying a selection, and there's no expectation that the selected sequences have the same GC as the genome as a whole.  This could also come from contamination from another source, or it could be a (quite strong) GC bias in the kit you're using.  Just from this graph alone it's difficult to say unfortunately.

**Comment by TendoLiu** [comment]
Thank you for the answer. I will think about it.
