### ISSUE TITLE
AdapterContent double counts some locations

### ISSUE THREAD

**Issue by al-dunstan** [s-andrews/FastQC#40]
The AdapterContent.Adapter inner class counts how often an adapter is found in the fasta reads.  After processing one fasta record (that has exactly one adapter in it) I think it's positions array should look something like this:

0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 

Instead, it looks like this:

0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2

It has one extra entry and, even though it's only processed one read and one adapter, it shows a count of two there at the end.

I wrote a more detailed explanation to help me figure out what was going on:

Assume AdapterContent.processSequence() is called with a single sequence
of length 15, and the sequence contains exactly one of the adapters (a really short adapter).

    What happens in the code                               Content of adapter.positions
    -----------------------------------------------        ----------------------------
    adapter.positions gets resized up to seq.length        000000000000000

    An adapter is found in seq at index=10,
    and we do this:

        for (i=index; i <= adapter.positions.length; i++)
            adapter.incrementCount(i)

    (The code says "i <= longestSequence - longestAdapter",
    but at this point that's how long adapter.positions is.)

    which translates into:

        adapter.incrementCount(10)                         000000000010000
        adapter.incrementCount(11)                         000000000011000
        adapter.incrementCount(12)                         000000000011100
        adapter.incrementCount(13)                         000000000011110
        adapter.incrementCount(14)                         000000000011111

    but when we do

        adapter.incrementCount(15)

    incrementCount() first resizes and extends             0000000000111111
    adapter.positions up to a length of (position + 1), or 16.

    and then it increments slot 15                         0000000000111112

So that after processing one sequence and one adapter we have a count of two adapters starting
in that last position.

I think it can be fixed in one of two ways.

1st way:
    Change the limits on that loop from
        i <= longestSequence - longestAdapter
    to
        i < longestSequence - longestAdapter

2nd way:
    Change the body of incrementCount() from

        if (position >= positions.length)
            expandLengthTo(position + 1);
        ++positions[position];

    to

        if (position >= positions.length)
            expandLengthTo(position + 1);
        else
            ++positions[position];

I'm inclined to do both.  The loop limit is knowingly going beyond the length of the array, the additional 'else' makes it explicit that we don't want to double-increment that last location.

I should add that, under certain circumstances, this makes the results dependent on the order in which the Sequence records arrive.

**Comment by s-andrews** [comment]
I had a look at this.  Unfortunately neither of the proposed solutions is a robust fix for the problem since it would break in the base where the adapter fragment was found exactly at the end of the sequence, where it would then be ignored.

The crux of this is that the expansion of the storage needs to happen before the incrementing starts, so we can't expand inside the ```incrementCount()``` function.  Alternatively we could also make this work by incrementing from the end back to the start, which might be an easier fix.

**Comment by s-andrews** [comment]
It turns out the length checking code was already present in the upstream processing function, it just wasn't expanding to the correct limit.  Once that's fixed then the expansion in the increment function is unnecessary and can be removed and the bug goes away.

Thanks for reporting this so clearly!
