### ISSUE TITLE
FASTQC in a pipeline

### ISSUE THREAD

**Issue by OrielResearchCure** [s-andrews/FastQC#47]
Hello,

I am trying to add FASTQC to my pipeline.
The installation on unix machine is the following:
```
["wget", "-O", "/opt/userowned/fastqc_v0.11.9.zip","https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip","--no-check-certificate"],
["unzip","-o" ,"-d" ,"/opt/userowned/", "/opt/userowned/fastqc_v0.11.9.zip"],
["chmod", "777", "/opt/userowned/FastQC/fastqc"],
```
When I am calling the FASTQC command from the code, the following error is being fired:

`Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /opt/userowned/FastQC/fastqc line 4.\nBEGIN failed--compilation aborted at /opt/userowned/FastQC/fastqc line 4.\nCommandException: No URLs matched: /opt/userowned/SRR4784332/FASTQC/*\nCommandException: 1 file/object could not be transferred.\n"`

Does the installation includes perl library? if not, what is the right way to install it?

Running which perl returns:
`/usr/bin/perl\`

Thanks,
eilalan

**Comment by s-andrews** [comment]
Thanks for reporting this.  ```FindBin``` is indeed a perl module which is required for FastQC to launch, however it is supposed to be a core module, which means that if you have Perl then you should have that module, which is why we don't check for it or mention it in the documentation.

https://perldoc.perl.org/index-modules-F.html

It would appear that something is therefore missing from your version of perl.  It could simply be that your OS has packaged the FindBin module in a separate OS package which isn't installed.  This should really be a dependency of the main perl package, but I know that, for example, redhat package perl-CGI (another core module) as an optional package.  You can probably therefore fix this by running an appropriate yum / apt command.  If you can let me know which distribution and version you're using I can have a look and see if I can track down specifically what you'd need to do.

**Comment by OrielResearchCure** [comment]
Thank you for the quick response. I was able to make a progress with that issue by executing perl and java. I have tested it on a stand alon debian machine. For the pipeline, the installation happens on the fly. following is the piece of code from the setup.py file
['apt-get', 'update'],
['apt-get', '--assume-yes', 'install', 'unzip'],
['apt-get', '--assume-yes', 'install', 'perl'],
['apt-get', '--assume-yes', 'install', 'default-jre'],
["wget", "-O", "/opt/userowned/fastqc_v0.11.9.zip","https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip","--no-check-certificate"],
["unzip","-o" ,"-d" ,"/opt/userowned/", "/opt/userowned/fastqc_v0.11.9.zip"],
["chmod", "777", "/opt/userowned/FastQC/fastqc"],

This is yet now working. The reason is that setuptools who executes the installation request was bot able to complete the installation.It is not FASTQC issue but you might be able to guide me from your experience.

The setup tools if failing after the first command of installation following the apt-get update. In the above order of execution, it fires and error after installing the unzip. The only way that I could make the setup.py pass was with one apt-get installation command following the apt-get update. I am addressing that issues with setup tools group. In case you have any idea how to resolve it, please let me know.
Thanks,
eilalan

**Comment by s-andrews** [comment]
I don't know why the subsequent apt install comands wouldn't work unless they are somehow being run in parallel?

One option might be to put all of the install comands in a single operation since apt should allow you to specify multiple packages.

```
['apt-get', '--assume-yes', 'install', 'unzip', 'perl', 'default-jre']
```

**Comment by OrielResearchCure** [comment]
Hi,
the issue was in installing java. I was able to installing it by copying the java .gz installation file into the pipeline worker machine.
The fASTQC is running successfully before the following error is being fired:

`Failed to process /opt/userowned/SRR7340414/FASTQC\njava.io.FileNotFoundException: /opt/userowned/SRR7340414/FASTQC (Is a directory)\n\tat java.base/java.io.FileInputStream.open0(Native Method)\n\tat java.base/java.io.FileInputStream.open(FileInputStream.java:212)\n\tat java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)\n\tat uk.ac.babraham.FastQC.Sequence.FastQFile.<init>(FastQFile.java:73)\n\tat uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:106)\n\tat uk.ac.babraham.FastQC.Sequence.SequenceFactory.getSequenceFile(SequenceFactory.java:62)\n\tat uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:159)\n\tat uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:121)\n\tat uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)\n'
`

The log of the FASTQC execution:

`stdout is b'Started analysis of SRR7340414_2.fastq\nApprox 5% complete for SRR7340414_2.fastq\nApprox 10% complete for SRR7340414_2.fastq\nApprox 15% complete for SRR7340414_2.fastq\nApprox 20% complete for SRR7340414_2.fastq\nApprox 25% complete for SRR7340414_2.fastq\nApprox 30% complete for SRR7340414_2.fastq\nApprox 35% complete for SRR7340414_2.fastq\nApprox 40% complete for SRR7340414_2.fastq\nApprox 45% complete for SRR7340414_2.fastq\nApprox 50% complete for SRR7340414_2.fastq\nApprox 55% complete for SRR7340414_2.fastq\nApprox 60% complete for SRR7340414_2.fastq\nApprox 65% complete for SRR7340414_2.fastq\nApprox 70% complete for SRR7340414_2.fastq\nApprox 75% complete for SRR7340414_2.fastq\nApprox 80% complete for SRR7340414_2.fastq\nApprox 85% complete for SRR7340414_2.fastq\nApprox 90% complete for SRR7340414_2.fastq\nApprox 95% complete for SRR7340414_2.fastq\nAnalysis complete for SRR7340414_2.fastq\n' `

Are you familiar with that error?

Thanks,
Eila

**Comment by s-andrews** [comment]
You seem to be describing two unrelated issues.  The initial one was nothing to do with either FastQC or Java, it was a missing module in your perl installation.  At the point where you got that error the only thing which had been run was the perl launch script - java hadn't been touched.

The last message you posted just looks like you either entered the path to the fastq file incorrectly, or possibly that you had a path with a space in it which wasn't quoted correctly.  You were trying to process ```/opt/userowned/SRR7340414/FASTQC``` which is a directory and not a file.  If the log of the session showed a successful completion then that probably means that two files were specified and one of them worked but fastqc still gave a non-zero exit code because of the other failure.  The original command line might have looked something like:

```fastqc /opt/userowned/SRR7340414/FASTQC /opt/userowned/SRR7340414/FASTQC/SRR7340414_2.fastq```

That would have produced something similar to what you saw (but I'm having to guess at the details).
