### ISSUE TITLE
Error Insecure dependency when run FastQC

### ISSUE THREAD

**Issue by tuan-cs** [s-andrews/FastQC#49]
I installed Miniconda3 and install Fastqc tool.
but when I run it with normal user, I meet the error here 
```
Insecure dependency in require while running setuid at /opt/miniconda3/bin/fastqc line 2.
BEGIN failed--compilation aborted at /opt/miniconda3/bin/fastqc line 2.
```

**Comment by s-andrews** [comment]
Why is anything running suid?  That's the root cause of this error, and it's not something which we set (or need) to work.  I can't think why you'd want that, and you can probably just remove those permissions to get things working, but it might be worth finding out why they're there.

Can you show me what the permissions are on the fastqc launch script?

```ls -l `which fastqc`  ```

**Comment by babytut** [comment]
thank you for your reply @s-andrews .
I install miniconda  it as root at /opt/miniconda.
Then install 
`conda install -c bioconda fastqc`
Here is permission on the fastqc launch script:

`lrwxrwxrwx 1 root root 27 Jun  1 16:04 /opt/miniconda3/bin/fastqc -> ../opt/fastqc-0.11.9/fastqc
`

**Comment by s-andrews** [comment]
Ah, OK, it's using a link so I can't see the actual permissions.  Can you give me:

```ls -l /opt/miniconda3/opt/fastqc-0.11.9```

**Comment by babytut** [comment]
Here is output

![image](https://user-images.githubusercontent.com/10155837/83479873-0a34d000-a4c4-11ea-8cbf-cff96ca4c339.png)

**Comment by s-andrews** [comment]
That's odd - I can't see any suid permissions on that file.  Suspiciously there is a file called "fastqc.orig" which isn't in our distribution, so I wonder if the launch script has been modified?

Can you show me the first few lines of:

```
/opt/miniconda3/opt/fastqc-0.11.9/fastqc
```

Can you also see what happens if you run:

```
/opt/miniconda3/opt/fastqc-0.11.9/fastqc.orig
```

**Comment by babytut** [comment]
Thank you for your support.  I install fastqc from Anaconda show maybe something different.

![image](https://user-images.githubusercontent.com/10155837/83504337-96f48380-a4ee-11ea-96bd-b12c03073eb5.png)

**Comment by s-andrews** [comment]
I think what's going on is that you've installed Anaconda as root and it's trying to use the sudo (suid) mechanism to *drop* privileges rather than gain them, but Perl doesn't care and just imposes its usual security restrictions because of the suid bit on the process.

The quickest fix would be to simply reinstall Anaconda as a normal user into your home directory and run it from there, which I think will work.  I'm not sure how to bypass the suid it's doing in the global sense, and if that's present then we'd have to do some path cleaning to get the perl security checks to pass.
