### ISSUE TITLE
Overrepresented Sequence Count

### ISSUE THREAD

**Issue by jrede** [s-andrews/FastQC#55]
How are the overrepresented sequences counted? After quality trimming and filtering, a sequence flagged as overrepresented increased. And after removing this sequence, ~ 200,000 paired ends were removed even though the count was ~ 25,000 for both forward and reverse reads. Thanks for any insight!

**Comment by s-andrews** [comment]
Overrepresented sequences are those which are identical over their entire length (or the first 50bp if the read length is over 75bp).  As with the duplication plot, which uses the same strategy, we only track the first 100,000 different sequences seen in the file, but those sequences are then counted exactly through the whole dataset so highly repeated sequences should be measured exactly every time as long as your file isn't being sorted or ordered.

FastQC will generally underestimate overrepreseted sequence counts, since it relies on an exact match, so even a single base miscall will cause a sequence to not be counted against the total.  Having poorer quality base calls will therefore tend to make the run look more diverse than it actually is since we can't tell the difference between true diversity and base calling errors.  Programs like adapter trimmers which are removing specific sequences will generally have some flexibility in them so may find more hits.  They also normally have some threshold for the amount of remaining sequence so if you had a small number of diverse bases followed by a fixed repeated sequence then the trimmer might remove these, but FastQC wouldn't consider them to be identical or over-represented.
