### ISSUE TITLE
Anyone working on xz support?

### ISSUE THREAD

**Issue by outpaddling** [s-andrews/FastQC#72]
xz provides substantially better compression than other tools.  Compression time is much longer at default and higher compression levels, but competitive at lower settings 0 to 3 while still providing a better compression ratio.  Decompression is reasonably fast at all levels.

Some benchmark data:

[https://www.rootusers.com/gzip-vs-bzip2-vs-xz-performance-comparison/](https://www.rootusers.com/gzip-vs-bzip2-vs-xz-performance-comparison/)

Thanks!

**Comment by s-andrews** [comment]
It's not something we've ever been asked for.  In practice all sequencers which generate fastq will use gzip so hardly anyone uses anything else (we put in bzip2 support because it got somewhat popular for a while but no one uses that much now).  It probably wouldn't be hard to add xz support as long as there's a suitable java decompressor for it, but it's honestly never come up before.

You can use xz compressed files with FastQC now by decompressing and then piping the stream to fastqc to get it to do the analysis.  Something like:

```
xzcat my_data.fastq.xz | fastqc stdin:my_data
```

**Comment by outpaddling** [comment]
Thanks, that's about what I've been doing (with fastqc and a couple other tools that don't support xz yet).  Would be nice if fastqc could handle this automatically if it's not too much trouble.  My sequence files are about 40% smaller with xz than with gz.

**Comment by s-andrews** [comment]
Hmm.  I had a look for java decompressors and found [this](https://tukaani.org/xz/java.html), but I also found [reports ](https://stackoverflow.com/questions/22421805/how-to-decompress-an-xz-file-faster-in-java)that it's horrifically slow, with no obvious alternatives so this might be significantly worse (slower) than piping in from an external binary decompressor.

**Comment by s-andrews** [comment]
Actually, I then found that there is an [xz decompressor](https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/compressors/xz/XZCompressorInputStream.html) in Apache commons, which is likely to be more efficient.

We already use this library for bzip2, so it might be super simple to add xz too...

**Comment by outpaddling** [comment]
Cool, thanks.  I would have assumed that adding xz alongside existing gzip and bzip2 support should be simple.

**Comment by outpaddling** [comment]
FYI, when running on a named pipe, fastqc generates a slew of "illegal seek" exceptions.  I discovered this adapting an example providing two paired-end input files, which I replaced with named pipes to get around the xz issue.  I'm guessing it doesn't know that the input is a pipe in this case.  In C, one could use do the following to detect it:
```
    struct stat fileinfo;
    fstat(fileno(stream), &fileinfo);
    if ( S_ISFIFO(fileinfo.st_mode) )
```
I imagine Java has something equivalent.
Correct me if I'm wrong, but I think fastqc does nothing differently when 2 files are provided to the same invocation.  So I can probably just run more processes with 1 input file each through an unnamed pipe and get the same results.

**Comment by s-andrews** [comment]
Thanks for reporting this.  I can't think of any reason why fastqc would behave differently if more than one file is supplied.  The processing is done the same way, with the files being put in a queue and doled out to worker threads to process as they become available.  It's just a really short queue with one file.

For the seek operations, the only case I can think of where  this would be a problem would be if you were reading compressed files through a named pipe.  I'm not familiar with the internal operations of the java gzip decompressor but I could imagine it doing this.  I would think that if you put uncompressed data into the pipe that that would probably fix it since the reads should then be completely sequential.

**Comment by outpaddling** [comment]
It is sending uncompressed data through the pipes:

```
xzcat $raw1 > $raw_fifo1 &
xzcat $raw2 > $raw_fifo2 &
xzcat $trimmed1 > $trimmed_fifo1 &
xzcat $trimmed2 > $trimmed_fifo2 &

# Background the first so we can use 4 cores per job
fastqc --threads=2 $raw_fifo1 $raw_fifo2 -o 2-qc/Raw &
fastqc --threads=2 $trimmed_fifo1 $trimmed_fifo2 -o 2-qc/Trimmed
```
I don't think seek() works on pipes in general.  My wild guess is that given a filename rather than reading from stdin, fastqc assumes it's a regular file.  That's just an idea to consider: I haven't looked into the code.

**Comment by s-andrews** [comment]
There's definintely nothing within the codebase which goes back through the file at any point, so it would only be if the java API through which the files are being read tried to do a seek for any reason.

I had a hunt and found [this ](https://github.com/samtools/htsjdk/issues/1084)which looks very relevant.  It seems that htsjdk also found this issue and did a lot of digging around it, but don't seem to have come to a conclusion about it.  The ```seek()``` operations come from the gzip decompressor or from ```BufferedInputStream```, both of which we use.  Looking at the code there is a bunch of logic which is different for stdin streams than for regular, files:

```
if (file.getName().startsWith("stdin")) {
    fileSize = Long.MAX_VALUE;
}
else {
    fileSize = file.length();
}

if (file.getName().startsWith("stdin")) {
    br = new BufferedReader(new InputStreamReader(System.in));
}
else if (file.getName().toLowerCase().endsWith(".gz")) {
    br = new BufferedReader(new InputStreamReader(new MultiMemberGZIPInputStream(fis)));
} 
else if (file.getName().toLowerCase().endsWith(".bz2")) {
    br = new BufferedReader(new InputStreamReader(new BZip2InputStream(fis,false)));
} 
else {
    br = new BufferedReader(new InputStreamReader(fis));
}
```
So it looks like I did figure out the changes needed to make this work correctly from a stream (it was a long time ago!), but it only detects this if you use the ```stdin:``` nomenclature - it's not going to work from named pipes because it will treat them as normal files.

I just had a quick look and there isn't a specific test in the file API in java for named pipes (someone suggested using isOther from NIO2 Files, which is pretty icky).  If there is a clean way to detect this then we could add that to the tests for stdin which might fix this.  In the mean time it looks like it should work if you use an explicit pipe rather than a named pipe.

**Comment by outpaddling** [comment]
So it looks like a named pipe will fall into the last case and be treated like a regular file.  In essence, it doesn't know it's reading from a pipe unless the filename contains stdin or a compression suffix.  Then it thinks it's OK to do a seek().

At this point I don't see a case for using named pipes, though.  I designed the script this way following an example with two files per fastqc invocation, assuming that specifying two file arguments meant something special.  Since I can get the same results without named pipes, the seek errors are a non-issue for me.  I verified that I don't get seek() errors with the following:

```
base_raw1=$(basename ${raw1%.fastq.xz})
base_raw2=$(basename ${raw2%.fastq.xz})
base_trimmed1=$(basename ${trimmed1%.fastq.xz})
base_trimmed2=$(basename ${trimmed2%.fastq.xz})

# Background the first three to run 4 jobs in parallel
xzcat $raw1 | fastqc --threads=2 -o Data/2-qc/Raw stdin:$base_raw1 &
xzcat $raw2 | fastqc --threads=2 -o Data/2-qc/Raw stdin:$base_raw2 &
xzcat $trimmed1 | fastqc --threads=2 -o Data/2-qc/Raw stdin:$base_trimmed1 &
xzcat $trimmed2 | fastqc --threads=2 -o Data/2-qc/Raw stdin:$base_trimmed2
```
So back to the original request.  It would be a nice convenience to directly support .xz files, though not urgent.

Thanks...

**Comment by s-andrews** [comment]
I'm doing a clean up of old issues.  Since this is the one and only request we've had for xz support, and given that there is a work round via pipes (though not named pipes), I'm going to close this.
