### ISSUE TITLE
How to run fastqc in various fastq.gz files, with different outputs

### ISSUE THREAD

**Issue by eibol1** [s-andrews/FastQC#80]
Hi,

I have many fastq.gz files obtained from the sequencer (raw data), for this example I have: file1 and file2 .fast.gz. I want to run fastqc in each of them but when I try to do this with `zcat file1.fastq.gz file2.fastq.gz | fastqc stdin --outdir=/some/path/results` I get only a report which I think is the fastqc mean from file1 and file2 (html and zip files)

What I want is one report for file1 and one report for file2. Can someone tell me how I can get these reports?  Is it possible to generate various stdin, like stdin1 and stdin2? I read that is not possible but I am not sure. 

If you need more information, please tell me. I am a beginner so maybe the info is incomplete. 

Thank you so much in advance!

**Comment by s-andrews** [comment]
If you have the files there then you don't need to use a pipe at all.  Just doing:

```fastqc file1.fastq.gz file2.fastq.gz file3.fastq.gz```

..will do what you're asking.  If you have multiple CPU cores available to you then you can even use the ```--threads=2``` (or however many you have) to process the files in parallel.

If you need to use a pipe for some reason then you can't generate multiple reports with a single command.  Once you do the ```zcat file1 file2 file3``` then there's no way for fastqc to know where the data from file1 ends and the data from file2 starts which is why you get a single report.  The only way to get multiple reports would be to start separate piped commands for each of the files.

```
zcat file1.fq.gz | fastqc stdin:report1
zcat file2.fq.gz | fastqc stdin:report2
zcat file3.fq.gz | fastqc stdin:report3
```

**Comment by s-andrews** [comment]
fastqc will handle the looping for you, so if you point it at multiple files it will process them one after the other.  If you give it multiple threads it will process that many files in parallel and queue the rest.

The only time it really gives you a benefit to submit individual files would be if you're submitting to a batch queue on a cluster where you want the cluster to handle the queuing for you.  Even then you can just use a simple bash loop:

```
for in *fastq.gz
do
qsub fastqc $i [or whatever the submission program is on your cluster]
done
```

**Comment by eibol1** [comment]
Thank you very much andrews. This helps me a lot!

**Comment by glzhang90095** [comment]
I found this if pretty straightforward by using find and execute through fastqc. The command is attached. Just set "./" as folder containing all your fastq.gz files and change "path to fastqc" to the path where the fastqc is installed.
find ./ -type f -name "*.fastq.gz" -exec "path to fastqc" '{}' \;
