### ISSUE TITLE
segmentation fault: 11

### ISSUE THREAD

**Issue by masashi4u** [s-andrews/FastQC#82]
Fastqc stopped working on my mac suddenly. The desktop version works perfectly. However, the command-line tool doesn't work. Even version check `fastqc --version` doesn't work. Surprisingly, Fastqc works on my laptop, which has identical versions of macOS and java. 

I tried to uninstall and re-install Fastqc by using Homebrew, Conda, or downloading manually. None of these attempts worked. 

The following is my running environment:
macOS 11.5.2 (Big Sur)
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

Does anyone have solutions/ideas?

**Comment by mbradyneeley** [comment]
Did you find a solution to this @masashi4u?

**Comment by s-andrews** [comment]
If it's a segmentation fault then it must be a crash in the java virtual machine, not in the fastqc code (which should generate a proper java exception if anything goes wrong).

My first thought would be to reinstall java itself since any problems or bugs there would be the likely cause.

**Comment by tmancill** [comment]
My suggestion is to uninstall Java 13 and install either the latest Java 11 release (11.0.15) or upgrade to Java 17 (17.0.3).  Both Java 11 and Java 17 are LTS (long-term-support) releases.

Java 13 is EOL [1,2] since March of 2020 and it's not going to be possible to get support for a bug in the JVM.  If you don't already have a preference, [Adoptium](https://adoptium.net/) produces OpenJDK builds for your platform. 

[1] https://endoflife.date/java
[2] https://www.oracle.com/java/technologies/java-se-support-roadmap.html
