### ISSUE TITLE
Allow choosing output filename path.

### ISSUE THREAD

**Issue by rhpvorderman** [s-andrews/FastQC#9]
FastQC is a very useful program. Thanks a lot!

We us it in pipelines and we stumble across the issue of the output filename path. This can't be defined by command line option. Only the output_dir can be defined.  So we know for certain in  which dir we have to look, but not what the folder with the output contents will be named.
The name of this folder is determined by this [regex](https://github.com/s-andrews/FastQC/blob/75df783702eb7a0a27fa2994a885f8a6fe4fa1b9/uk/ac/babraham/FastQC/Analysis/OfflineRunner.java#L170) in the code:
```
		if (FastQCConfig.getInstance().output_dir != null) {
			String fileName = file.getFile().getName().replaceAll("stdin:","").replaceAll("\\.gz$","").replaceAll("\\.bz2$","").replaceAll("\\.txt$","").replaceAll("\\.fastq$", "").replaceAll("\\.fq$", "").replaceAll("\\.csfastq$", "").replaceAll("\\.sam$", "").replaceAll("\\.bam$", "")+"_fastqc.html";
			reportFile = new File(FastQCConfig.getInstance().output_dir+"/"+fileName);						
}
```
Is it possible to have `fileName` set by command line option?

**Comment by s-andrews** [comment]
The reason we have this as a directory, rather than a file level option is that the input to fastqc is (at least potentially) a set of files, so a single output name isn't enough.

The workround to get a specific filename if you're only processing a single file is to use the streaming mode of fastqc, where you pipe the data into the program instead of reading from a file.

eg:

```
[andrewss@rocks1 NameTest]$ ls
small.fq

[andrewss@rocks1 NameTest]$ cat small.fq | fastqc stdin:myname
Started analysis of stdin:myname
Analysis complete for stdin:myname
[andrewss@rocks1 NameTest]$ ls
myname_fastqc.html  myname_fastqc.zip  small.fq
```

Does this let you do what you need?

**Comment by rhpvorderman** [comment]
Yes, thanks a lot!

Personally I would prefer that fastqc does not do all this regex replace stuff and would just use `filename + '.d'` but that would of course break backwards compatibility in a massive way. 
Thank you for your fast reply!

**Comment by bioXiaoheng** [comment]
> The reason we have this as a directory, rather than a file level option is that the input to fastqc is (at least potentially) a set of files, so a single output name isn't enough.
> 
> The workround to get a specific filename if you're only processing a single file is to use the streaming mode of fastqc, where you pipe the data into the program instead of reading from a file.
> 
> eg:
> 
> ```
> [andrewss@rocks1 NameTest]$ ls
> small.fq
> 
> [andrewss@rocks1 NameTest]$ cat small.fq | fastqc stdin:myname
> Started analysis of stdin:myname
> Analysis complete for stdin:myname
> [andrewss@rocks1 NameTest]$ ls
> myname_fastqc.html  myname_fastqc.zip  small.fq
> ```
> Does this let you do what you need?

Hi!
Does this feature only exist in newer versions of fastQC? I see that the newest version is v0.11.8, but the one available on our cluster is v0.11.2. Or is this feature not compatible with zcat...? When I tried
`[]$ zcat fastqs/Name_1.fastq.gz | fastqc stdin:Name`
It always reported
`Skipping 'stdin:Name' which didn't exist, or couldn't be read`

**Comment by s-andrews** [comment]
This feature came in with v0.11.6 so you'll need that or newer to use it.

**Comment by rhpvorderman** [comment]
@bioXiaoheng you can use [bioconda](http://bioconda.github.io/) if you need [versions of fastqc](http://bioconda.github.io/recipes/fastqc/README.html) that are newer than on your cluster.

**Comment by bioXiaoheng** [comment]
Thanks for the suggestions!

**Comment by dariober** [comment]
I had the same issue/request. Using `stdin:myname` almost works for me except the standard input needs to be uncompressed and I don't know beforehand whether my input file is going to be uncompressed, gzip'd or bzip'd. 

A quick solution is to use [cutadapt](https://cutadapt.readthedocs.io/en/stable/) if you already have it. With default options, cutadapt streams the input fastq uncompressed to stdout. E.g.:

```
cutadapt --quiet test.txt.bz2 | fastqc stdin:testqc
```

A quick test with cutadapt 4.0 seems to work ok. I link Issue #14 since it's related. My 2p-
