### ISSUE TITLE
Combine multiple fastqc_data.txt from a single FASTQ

### ISSUE THREAD

**Issue by michaeljon** [s-andrews/FastQC#96]
We're fragmenting 50x and 100x WGS paired end FASTQs into a larger number of smaller files so we can run FASTQC over them in a reasonable time and to take advantage of our multicore compute nodes. I'm wondering if anyone has a tool that'll take a number of fastqc_data.txt files from a single sample and combine them back into a single file. Our current approach uses 128 files per input FASTQ. I don't have a problem writing one but would be more than happy to use someone else's already tested work.

thanks

**Comment by s-andrews** [comment]
If your data is so big that the runtime is an issue then I'm not sure that you're going to get much benefit from going through the hassle of splitting the files and recombining the reports.  Just taking a suitably large random sample of the data and creating a report from that will get you pretty much identical results to analysing the whole thing.  Problems identified in the QC are properties of the library so random sampling should be an effective way to fix this.

Just be aware that if your data comes straight off the sequencer that just analysing the reads at the start of the file will probably give an overly pessimistic view of the data since the initial reads come from the edge of the flowcell and are usually of lower quality than the library as a whole.  Sampling across the whole file will give a better result (but will be slower as you have to read the whole file).

As an alternative, if you just want to combine the results of multiple runs into a single report then you could look at MultiQC which does this very nicely already.  We use this for combining results from multiple different libraries in the same experiment, but it would equally work for multiple subsets of the same library, and would give you a nice view of whether you actually need to analyse all of the subsets.

**Comment by michaeljon** [comment]
Thanks. That was my thought this morning - just grab some sample from throughout the file(s). When I eyeballed the .txt files I noticed that they're nearly "identical" across the batch so pulling any one of them should provide our QC team with the data they need to continue.
